import img1 from "../../assets/Zdjecia/img1.jpg";
import img2 from "../../assets/Zdjecia/img2.jpg";

export const GaleriaItems = [
  {
    Title: "Mecz ksbaranowice zory vs rybnik",
    url: "Mecz-ksbaranowice-zory-vs-rybnik",
    thumbnail: img1,
    img: [img1, img1, img1, img1, img1, img2],
    date: "12.12.2003",
    info: "I drużyna",
    span: "więcej",
    photographer: "Pan fotograf",
    id: 1,
  },
  {
    Title: "ehhhdhdfhfdgdfgdf12312312312gfh",
    url: "ehhh",
    thumbnail: img2,
    img: [img2, img1, img2, img1, img2, img1],
    date: "2.2.2222",
    info: "rezerwa",
    span: "więcej",
    photographer: "Pani fotograf",
    id: 2,
  },
  {
    Title: "ehhhdhdfhfdgdfgdf12312312312gfh",
    url: "ehhh",
    thumbnail: img2,
    img: [img2, img1, img2, img1, img2, img1],
    date: "2.2.2222",
    info: "rezerwa",
    span: "więcej",
    photographer: "Pani fotograf",
    id: 3,
  },
  {
    Title: "Mecz ksbaranowice zory vs rybnik",
    url: "Mecz-ksbaranowice-zory-vs-rybnik",
    thumbnail: img1,
    img: [img1, img1, img1, img1, img1, img2],
    date: "12.12.2003",
    info: "I drużyna",
    span: "więcej",
    photographer: "Pan fotograf",
    id: 4,
  },
  {
    Title: "ehhhdhdfhfdgdfgdf12312312312gfh",
    url: "ehhh",
    thumbnail: img2,
    img: [img2, img1, img2, img1, img2, img1],
    date: "2.2.2222",
    info: "rezerwa",
    span: "więcej",
    photographer: "Pani fotograf",
    id: 5,
  },
  {
    Title: "ehhhdhdfhfdgdfgdf12312312312gfh",
    url: "ehhh",
    thumbnail: img2,
    img: [img2, img1, img2, img1, img2, img1],
    date: "2.2.2222",
    info: "rezerwa",
    span: "więcej",
    photographer: "Pani fotograf",
    id: 6,
  },
  {
    Title: "Mecz ksbaranowice zory vs rybnik",
    url: "Mecz-ksbaranowice-zory-vs-rybnik",
    thumbnail: img1,
    img: [img1, img1, img1, img1, img1, img2],
    date: "12.12.2003",
    info: "I drużyna",
    span: "więcej",
    photographer: "Pan fotograf",
    id: 7,
  },
  {
    Title: "ehhhdhdfhfdgdfgdf12312312312gfh",
    url: "ehhh",
    thumbnail: img2,
    img: [img2, img1, img2, img1, img2, img1],
    date: "2.2.2222",
    info: "rezerwa",
    span: "więcej",
    photographer: "Pani fotograf",
    id: 8,
  },
  {
    Title: "ehhhdhdfhfdgdfgdf12312312312gfh",
    url: "ehhh",
    thumbnail: img2,
    img: [img2, img1, img2, img1, img2, img1],
    date: "2.2.2222",
    info: "rezerwa",
    span: "więcej",
    photographer: "Pani fotograf",
    id: 9,
  },
  {
    Title: "Mecz ksbaranowice zory vs rybnik",
    url: "Mecz-ksbaranowice-zory-vs-rybnik",
    thumbnail: img1,
    img: [img1, img1, img1, img1, img1, img2],
    date: "12.12.2003",
    info: "I drużyna",
    span: "więcej",
    photographer: "Pan fotograf",
    id: 10,
  },
  {
    Title: "ehhhdhdfhfdgdfgdf12312312312gfh",
    url: "ehhh",
    thumbnail: img2,
    img: [img2, img1, img2, img1, img2, img1],
    date: "2.2.2222",
    info: "rezerwa",
    span: "więcej",
    photographer: "Pani fotograf",
    id: 11,
  },
  {
    Title: "ehhhdhdfhfdgdfgdf12312312312gfh",
    url: "ehhh",
    thumbnail: img2,
    img: [img2, img1, img2, img1, img2, img1],
    date: "2.2.2222",
    info: "rezerwa",
    span: "więcej",
    photographer: "Pani fotograf",
    id: 12,
  },
  {
    Title: "Mecz ksbaranowice zory vs rybnik",
    url: "Mecz-ksbaranowice-zory-vs-rybnik",
    thumbnail: img1,
    img: [img1, img1, img1, img1, img1, img2],
    date: "12.12.2003",
    info: "I drużyna",
    span: "więcej",
    photographer: "Pan fotograf",
    id: 13,
  },
  {
    Title: "ehhhdhdfhfdgdfgdf12312312312gfh",
    url: "ehhh",
    thumbnail: img2,
    img: [img2, img1, img2, img1, img2, img1],
    date: "2.2.2222",
    info: "rezerwa",
    span: "więcej",
    photographer: "Pani fotograf",
    id: 14,
  },
  {
    Title: "ehhhdhdfhfdgdfgdf12312312312gfh",
    url: "ehhh",
    thumbnail: img2,
    img: [img2, img1, img2, img1, img2, img1],
    date: "2.2.2222",
    info: "rezerwa",
    span: "więcej",
    photographer: "Pani fotograf",
    id: 15,
  },
  {
    Title: "Mecz ksbaranowice zory vs rybnik",
    url: "Mecz-ksbaranowice-zory-vs-rybnik",
    thumbnail: img1,
    img: [img1, img1, img1, img1, img1, img2],
    date: "12.12.2003",
    info: "I drużyna",
    span: "więcej",
    photographer: "Pan fotograf",
    id: 16,
  },
  {
    Title: "ehhhdhdfhfdgdfgdf12312312312gfh",
    url: "ehhh",
    thumbnail: img2,
    img: [img2, img1, img2, img1, img2, img1],
    date: "2.2.2222",
    info: "rezerwa",
    span: "więcej",
    photographer: "Pani fotograf",
    id: 17,
  },
  {
    Title: "ehhhdhdfhfdgdfgdf12312312312gfh",
    url: "ehhh",
    thumbnail: img2,
    img: [img2, img1, img2, img1, img2, img1],
    date: "2.2.2222",
    info: "rezerwa",
    span: "więcej",
    photographer: "Pani fotograf",
    id: 18,
  },
  {
    Title: "Mecz ksbaranowice zory vs rybnik",
    url: "Mecz-ksbaranowice-zory-vs-rybnik",
    thumbnail: img1,
    img: [img1, img1, img1, img1, img1, img2],
    date: "12.12.2003",
    info: "I drużyna",
    span: "więcej",
    photographer: "Pan fotograf",
    id: 19,
  },
  {
    Title: "ehhhdhdfhfdgdfgdf12312312312gfh",
    url: "ehhh",
    thumbnail: img2,
    img: [img2, img1, img2, img1, img2, img1],
    date: "2.2.2222",
    info: "rezerwa",
    span: "więcej",
    photographer: "Pani fotograf",
    id: 20,
  },
  {
    Title: "ehhhdhdfhfdgdfgdf12312312312gfh",
    url: "ehhh",
    thumbnail: img2,
    img: [img2, img1, img2, img1, img2, img1],
    date: "2.2.2222",
    info: "rezerwa",
    span: "więcej",
    photographer: "Pani fotograf",
    id: 21,
  },
  {
    Title: "Mecz ksbaranowice zory vs rybnik",
    url: "Mecz-ksbaranowice-zory-vs-rybnik",
    thumbnail: img1,
    img: [img1, img1, img1, img1, img1, img2],
    date: "12.12.2003",
    info: "I drużyna",
    span: "więcej",
    photographer: "Pan fotograf",
    id: 22,
  },
  {
    Title: "ehhhdhdfhfdgdfgdf12312312312gfh",
    url: "ehhh",
    thumbnail: img2,
    img: [img2, img1, img2, img1, img2, img1],
    date: "2.2.2222",
    info: "rezerwa",
    span: "więcej",
    photographer: "Pani fotograf",
    id: 23,
  },
  {
    Title: "ehhhdhdfhfdgdfgdf12312312312gfh",
    url: "ehhh",
    thumbnail: img2,
    img: [img2, img1, img2, img1, img2, img1],
    date: "2.2.2222",
    info: "rezerwa",
    span: "więcej",
    photographer: "Pani fotograf",
    id: 24,
  },
  {
    Title: "Mecz ksbaranowice zory vs rybnik",
    url: "Mecz-ksbaranowice-zory-vs-rybnik",
    thumbnail: img1,
    img: [img1, img1, img1, img1, img1, img2],
    date: "12.12.2003",
    info: "I drużyna",
    span: "więcej",
    photographer: "Pan fotograf",
    id: 25,
  },
  {
    Title: "ehhhdhdfhfdgdfgdf12312312312gfh",
    url: "ehhh",
    thumbnail: img2,
    img: [img2, img1, img2, img1, img2, img1],
    date: "2.2.2222",
    info: "rezerwa",
    span: "więcej",
    photographer: "Pani fotograf",
    id: 26,
  },
  {
    Title: "ehhhdhdfhfdgdfgdf12312312312gfh",
    url: "ehhh",
    thumbnail: img2,
    img: [img2, img1, img2, img1, img2, img1],
    date: "2.2.2222",
    info: "rezerwa",
    span: "więcej",
    photographer: "Pani fotograf",
    id: 27,
  },
];
